### ISSUE TITLE
关于运行速度

### ISSUE THREAD

**Issue by fb029ed** [echocatzh/torch-mfcc#1]
您好，对您使用gpu加速音频特征提取的研究非常感兴趣，想问一下，您有加速前后的速度比较吗？

**Comment by echocatzh** [comment]
gpu实现stft目的：1. 提高gpu利用率，减少cpu负荷。2. 使stft和istft过程可导。
我刚才测试了一下stft过程的速度对比，其中cpu使用的是librosa中的stft函数，即numpy的fft，我个人认为numpy的fft算是python里面优化细节很多的一种实现方式了。
对比可以看出速度能够快一倍，但这减少了cpu的负担。如果考虑加上inverse stft，应该会更有所提升。
![image](https://user-images.githubusercontent.com/25864429/105476380-85f5be00-5cdb-11eb-8c98-0b0c375f55fd.png)
